name: Run Cart Manager Agent Initializer

on:
  push:
    paths:
      - 'src/app/agents/cartManagerAgent_initializer.py'
      - 'src/prompts/CartManager.txt'
      - '.github/workflows/run-cart-manager-agent.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-cart-manager-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Login via Azure CLI
        uses: azure/login@v2.1.1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Cart Manager Agent Initializer
        run: |
          cd src/
          python app/agents/cartManagerAgent_initializer.py
